name: tvmaze
description: TV Maze

publish_to: 'none'

version: 1.0.0+202203061

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_html: ^2.2.1
  shimmer: ^2.0.0
  expandable: ^5.0.1
  modal_bottom_sheet: ^2.0.0
  moor_flutter: ^4.0.0
  bottom_navy_bar: ^6.0.0
  google_fonts: ^2.3.1
  flutter_slidable: ^1.2.0
  intl:
  flutter_dotenv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  path_provider: ^2.0.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - env/